version: "3.9"

services:

  db:
    image: postgres:16.1
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: energies
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  pg-admin:
    image: dpage/pgadmin4:8.2
    container_name: pg-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: simon.nogaret.ns@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    ports:
      - 80:80

volumes:
  postgres-data:
  pg-admin-data:
    